Re-generate .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,85 +1,107 @@
-# NB: don't set `language: haskell` here
-
+# This file has been generated -- see https://github.com/hvr/multi-ghc-travis
+language: c
 sudo: false
-
-# The following enables several GHC versions to be tested; often it's enough to test only against the last release in a major GHC version. Feel free to omit lines listings versions you don't need/want testing for.
-# Note that this setup uses Cabal sandboxes, so we need at least cabal-install-1.18.
-matrix:
- fast_finish: true
- include:
-  - env: CABALVER=1.18 GHCVER=7.0.4
-    addons: {apt: {packages: [cabal-install-1.18, ghc-7.0.4], sources: [hvr-ghc]}}
-  - env: CABALVER=1.18 GHCVER=7.2.2
-    addons: {apt: {packages: [cabal-install-1.18, ghc-7.2.2], sources: [hvr-ghc]}}
-  - env: CABALVER=1.18 GHCVER=7.4.2
-    addons: {apt: {packages: [cabal-install-1.18, ghc-7.4.2], sources: [hvr-ghc]}}
-  - env: CABALVER=1.18 GHCVER=7.6.3
-    addons: {apt: {packages: [cabal-install-1.18, ghc-7.6.3], sources: [hvr-ghc]}}
-  - env: CABALVER=1.20 GHCVER=7.8.4
-    addons: {apt: {packages: [cabal-install-1.20, ghc-7.8.4], sources: [hvr-ghc]}}
-  - env: CABALVER=1.22 GHCVER=7.10.1
-    addons: {apt: {packages: [cabal-install-1.22, ghc-7.10.1],sources: [hvr-ghc]}}
-  - env: CABALVER=head GHCVER=head
-    addons: {apt: {packages: [cabal-install-head,ghc-head],  sources: [hvr-ghc]}}
-
- allow_failures:
-  - env: CABALVER=head GHCVER=head
 
 cache:
   directories:
-    - $HOME/.cabal
-    - $HOME/.ghc
+    - $HOME/.cabsnap
+    - $HOME/.cabal/packages
 
-before-cache:
-  # Don't cache the Hackage index
-  - rm -rf $HOME/cabal/packages/hackage.haskell.org
+before_cache:
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar
 
-# Note: the distinction between `before_install` and `install` is not important.
+# Using sandboxes, so need cabal-install >= 1.18
+matrix:
+  fast_finish: true
+  include:
+    - env: CABALVER=1.18 GHCVER=7.4.2
+      compiler: ": #GHC 7.4.2"
+      addons: {apt: {packages: [cabal-install-1.18,ghc-7.4.2], sources: [hvr-ghc]}}
+    - env: CABALVER=1.18 GHCVER=7.6.3
+      compiler: ": #GHC 7.6.3"
+      addons: {apt: {packages: [cabal-install-1.18,ghc-7.6.3], sources: [hvr-ghc]}}
+    - env: CABALVER=1.18 GHCVER=7.8.4
+      compiler: ": #GHC 7.8.4"
+      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4], sources: [hvr-ghc]}}
+    - env: CABALVER=1.22 GHCVER=7.10.2
+      compiler: ": #GHC 7.10.2"
+      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2], sources: [hvr-ghc]}}
+    - env: CABALVER=head GHCVER=head
+      compiler: ": #GHC head"
+      addons: {apt: {packages: [cabal-install-head,ghc-head], sources: [hvr-ghc]}}
+
+  allow_failures:
+    - env: CABALVER=head GHCVER=head
+
 before_install:
-  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
-  - uname -a
+ - unset CC
+ - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 
 install:
-  - cabal --version
-  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
-  - ghc --info
-  - travis_retry cabal update
-  - cabal install -j -O2 packdeps
-  - cabal sandbox init
-  - cabal install -j --only-dependencies --enable-tests --enable-benchmarks
+ - cabal --version
+ - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
+ - if [ -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz ];
+   then
+     zcat $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz >
+          $HOME/.cabal/packages/hackage.haskell.org/00-index.tar;
+   fi
+ - travis_retry cabal update -v
+ - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
+ - cabal install --only-dependencies --enable-tests --enable-benchmarks --dry -v > installplan.txt
+ - sed -i -e '1,/^Resolving /d' installplan.txt; cat installplan.txt
 
-# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
+# check whether current requested install-plan matches cached package-db snapshot
+ - if diff -u installplan.txt $HOME/.cabsnap/installplan.txt;
+   then
+     echo "cabal build-cache HIT";
+     rm -rfv .ghc;
+     cp -a $HOME/.cabsnap/ghc $HOME/.ghc;
+     cp -a $HOME/.cabsnap/lib $HOME/.cabsnap/share $HOME/.cabsnap/bin $HOME/.cabal/;
+   else
+     echo "cabal build-cache MISS";
+     rm -rf $HOME/.cabsnap;
+     mkdir -p $HOME/.ghc $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin;
+     cabal install --only-dependencies --enable-tests --enable-benchmarks;
+   fi
+
+# snapshot package-db on cache miss
+ - if [ ! -d $HOME/.cabsnap ];
+   then
+      echo "snapshotting package-db to build-cache";
+      mkdir $HOME/.cabsnap;
+      cp -a $HOME/.ghc $HOME/.cabsnap/ghc;
+      cp -a $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin installplan.txt $HOME/.cabsnap/;
+   fi
+
+# Here starts the actual work to be performed for the package under test;
+# any command which exits with a non-zero exit code causes the build to fail.
 script:
+ - if [ -f configure.ac ]; then autoreconf -i; fi
  - cabal configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
  - cabal build   # this builds all libraries and executables (including tests/benchmarks)
  - cabal test
  - cabal check
  - cabal sdist   # tests that a source-distribution can be generated
- - cabal --version | grep --quiet '1.22';
-   if [ $? -eq 0 ]; then
-      cabal exec packdeps fgl.cabal;
-   fi
 
-# The following scriptlet checks that the resulting source distribution can be built & installed
- - function install_from_tarball {
-   export SRC_TGZ=$(cabal-$CABALVER info . | awk '{print $2 ".tar.gz";exit}') ;
-   if [ -f "dist/$SRC_TGZ" ]; then
-      cabal install "dist/$SRC_TGZ" -v2;
-   else
-      echo "expected 'dist/$SRC_TGZ' not found";
-      exit 1;
-   fi
-   }
- - install_from_tarball
+# Check that the resulting source distribution can be built & installed.
+# If there are no other `.tar.gz` files in `dist`, this can be even simpler:
+# `cabal install --force-reinstalls dist/*-*.tar.gz`
+ - SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
+   (cd dist && cabal install --force-reinstalls "$SRC_TGZ")
 
 # Check the fgl-arbitrary sub-package
  - cd fgl-arbitrary
- - cabal sandbox init
- - cabal sandbox add-source ../
+ # Relying upon fgl being installed above when testing sdist, and that
+ # it doesn't require any other dependencies not used by fgl.
  - cabal install --dependencies-only --enable-tests --enable-benchmarks
  - cabal configure --enable-tests --enable-benchmarks -v2
  - cabal build
  - cabal test
  - cabal check
  - cabal sdist
- - install_from_tarball
+ - SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
+   (cd dist && cabal install --force-reinstalls "$SRC_TGZ")
+
+
+# EOF
